server:
  port: 9000
spring:
  application:
    name: disbursement-web-application
  datasource:
    url: jdbc:postgresql://localhost:5432/disbursements
    username: sequra
    password: sequrachallenge123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      #      Enabled only to generate table and database stuffs
      ddl-auto: create
  flyway:
    baseline-on-migrate: true
    out-of-order: true
    # disable when use hibernate only
    enabled: false