spring:
  datasource:
    url: jdbc:postgresql://postgresql_service:5432/disbursements
    username: sequra
    password: sequrachallenge123
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    out-of-order: true